# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d407dd26b53a4a72ccad9f2b0a34caabc4f1c025c3fdcbd75f66784c3d21ab548d0b53bcd8e5ddc2c8cc712b3c9a629cc4f7c4c05bd6c45205a1f0c99091002d

test:
  secret_key_base: 5972d12ef745a5dea1b3bb3f4d4a67db33a10a2cb0a65e96bedb19c7b0d5470fe5d6f49e89ce3cdbd2a516e40bd9ec82d1e078882355e5708de1e46f1a8fba3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
